node {
    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        docker.image('python:2-alpine').inside {
            sh 'python -m py_compile ./sources/add2vals.py ./sources/calc.py'
        }
    }

    stage('Test') {
        docker.image('qnib/pytest').inside {
            sh 'py.test --verbose --junitxml=test-reports/results.xml ./sources/test_calc.py'
        }
        junit 'test-reports/results.xml'
    }

    stage('Deploy') {
         docker.image('python:2-alpine').inside {
            sh '''
            WORKSPACE=$(pwd)
            mkdir -p $WORKSPACE/app
            cp -r ./sources $WORKSPACE/app
            nohup python $WORKSPACE/app/sources/add2vals.py > $WORKSPACE/app/app.log 2>&1 &
            '''
    }
    archiveArtifacts artifacts: 'app/**', fingerprint: true

    echo "Aplikasi berjalan selama 1 menit"
    sleep(time: 1, unit: 'MINUTES')
}

}
