node {
    def pyCompileImage = 'python:2-alpine'
    def pytestImage = 'qnib/pytest'
    def pyInstallerImage = 'cdrx/pyinstaller-linux:python2'

    try {
        stage('Build') {
            dockerImage = docker.image(pyCompileImage)
            dockerImage.pull()
            dockerImage.inside('-v /var/jenkins_home/workspace:/workspace -w /workspace') {
               sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }

        stage('Test') {
            dockerImage = docker.image(pytestImage)
            dockerImage.pull()
            dockerImage.inside {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            junit 'test-reports/results.xml'
        }

        stage('Deliver') {
            dockerImage = docker.image(pyInstallerImage)
            dockerImage.pull()
            dockerImage.inside {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            archiveArtifacts 'dist/add2vals'
        }
    } catch (Exception e) {
        currentBuild.result = 'FAILURE'
        throw e
    }
}
